stages:
  - build
  - test
build website:
  stage: build
#  docker image to use
  image: node
  script:
    - npm install
#    - npm test
    - npm run build
#  save build artifacts in build directory
  artifacts:
    paths:
      - build/

test artifact:
  image: alpine
  stage: test
  script:
#   favicon is attached by webpack
    - grep -q "icon" ./build/index.html
#   bundle.js is attached by webpack
    - grep -q "bundle.js" ./build/index.html
#    you can potentially check last exit code by $ echo $?

test website:
  image: node
  stage: test
  script:
    - npm install
#    npm start alone would block CLI
    - npm start &
    - sleep 3
#    download the website
    - curl "http://localhost:9999" | tac | tac | grep -q "canvas"