import {configure, shallow} from 'enzyme';
// shallow does not render children components
import Adapter from 'enzyme-adapter-react-16';
import React from 'react'
import Canvas from "./Canvas";

configure({
    adapter: new Adapter()
})

describe('<Canvas/>', () => {
    let wrapper;
    // do this before executing all test it()
    beforeEach(()=>{
        wrapper = shallow(<Canvas/>)
    })

    it('Should ', () => {
        wrapper.setProps({width: "256px"})
        expect(wrapper.contains(<p>Image is generated by web worker.</p>)).toEqual(true)
    })

    // see docs for more functionalities
    // mock functions: mock async api calls
    // full rendering with mount() looks at the entire component tree
})
